apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/foody-default: "true"
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-service:8761/eureka
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_URL
              value: jdbc:postgresql://user-db.default.svc.cluster.local:5433/user-db?enabledTLSProtocols=TLSv1.2
            - name: POSTGRES_USER
              value: admin
            - name: SPRING_RABBITMQ_HOST
              value: rabbitMQ
          image: innaxn/foody-user-service:latest
          name: user-microservice
          ports:
            - containerPort: 8082
              hostPort: 8082
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
